# extra records, included from example.org.yaml
records:
    -
        name: extra
        type: A
        value: 1.2.3.4
        ttl: 300
    -
        name: demo
        type: A
        value: 5.6.7.8
        ttl: 600
