name: example.org
targets:
    - transip-alice
    - transip-bob
records:
    -
        name: www
        type: A
        value: 93.184.215.14
        ttl: 300
    -
        name: mail
        type: A
        value: 93.184.215.14
        ttl: 300
    -
        name: "@10"
        type: MX
        value: mail.example.org.
        ttl: 300
